source 'https://rubygems.org'

gem 'cpf_utils', '1.3.0'
gem 'faker'

# bundle install -> instala as gems listadas em Gemfile

# versões:
# exata: '1.3.0'
# igual ou maior: >=1.3.0'
# aproximadamente: ~>1.3.0' -> até 1.9.9
